### ISSUE TITLE
Enable discussions?

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.releng#148]
@akurtakov do you mind enabling discussions for this repository? I think it would be good for general releng questions/discussions.

**Comment by akurtakov** [comment]
Looks like I can't do it for this one . Opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2249 for webmaster to help with it.

**Comment by laeubi** [comment]
Maybe only project-leads can do that (has releng different project leads than platform?)

**Comment by akurtakov** [comment]
Same ones (incl. me) so it must be some setup issue.

**Comment by akurtakov** [comment]
Should be working now.
