### ISSUE TITLE
Preparations for publishing 4.26 to Maven

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.releng#152]
I wanted to plan ahead to record what I think needs attention to properly published the 4.26 release to Maven central...

The following file needs updating probably:

https://github.com/eclipse-platform/eclipse.platform.releng/blob/master/publish-to-maven-central/baseline.txt

But it wasn't updated for the 4.25 release:

![image](https://user-images.githubusercontent.com/208716/204818579-5d0a85f2-57b3-40e9-b31b-2e60aac79359.png)

This needs updating, but can't be updated until the release is available in the drops4 folder:

https://github.com/eclipse-platform/eclipse.platform.releng/blob/c9a0d76ea29c8119922c6e4afd841e29220f19f4/publish-to-maven-central/properties.sh#L15-L22

This always fails when we build the snapshot versions and should be fixed

https://github.com/eclipse-platform/eclipse.platform.releng/blob/c9a0d76ea29c8119922c6e4afd841e29220f19f4/publish-to-maven-central/CBIaggregator.sh#L388-L389

This is likely a problem too:

https://github.com/eclipse-platform/eclipse.platform.releng/blob/c9a0d76ea29c8119922c6e4afd841e29220f19f4/publish-to-maven-central/publishJDT.sh#L119-L128

These three references to the 4.26-I-Builds probably need attention too because there appear to be 2 I-Build after the RC2 version:

https://github.com/eclipse-platform/eclipse.platform.releng/blob/c9a0d76ea29c8119922c6e4afd841e29220f19f4/publish-to-maven-central/SDK4Mvn.aggr#L4-L20

**Comment by merks** [comment]
@SDawley I think you have covered most of these things, but I'm not sure if you were aware that this issue is open.

**Comment by SDawley** [comment]
I've updated baseline.txt with the new baseline from this release:
https://github.com/eclipse-platform/eclipse.platform.releng/pull/159

**Comment by merks** [comment]
Note that all the things I carefully enumerated above were not done.  I still see this:
```
# WORKAROUND TO PUBLISH ECJ SOURCES AS REQUESTED BY NEXUS
# PRETTY FRAGILE! NEEDS VERSION UPDATES ON EVERY STREAM
# suggested fix: https://github.com/eclipse-jdt/eclipse.jdt.core/issues/384
wget https://download.eclipse.org/eclipse/downloads/drops4/R-4.25-202208311800/download.php?dropFile=ecjsrc-4.25.jar -o ecjsrc.jar
for pomFile in org/eclipse/jdt/ecj/*/ecj-*.pom; do
	${MVN} -f jdt-pom.xml -s ${SETTINGS} gpg:sign-and-deploy-file \
		-Durl=${URL} -DrepositoryId=${REPO} \
		-Dfile=ecjsrc.jar -DpomFile=${pomFile} -Dclassifier=sources \
		>> .log/sources-upload.txt
done
```
Hopefully that will go away with the restructuring of the batch compiler for 4.27.
