### ISSUE TITLE
Plan for 2023-06 (4.28) release

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#200]
Continuation of #189 for 4.28 release.

As of today, https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_28.xml shows 404 error.

Here is how it should look like:
https://www.eclipse.org/projects/project-plan.php?planurl=https://www.eclipse.org/eclipse/development/plans/eclipse_project_plan_4_27.xml

**Comment by iloveeclipse** [comment]
@akurtakov, @sravanlakkimsetti and all who care:

It would be nice we would finally create a plan for 4.28 :-)

I can do that boring work, but first few things should be made clear.

Do we have a clear understanding / agreement regarding "target requirements"?
- Java 17 is minimal supported one. Should be agreed / announced already.
- What about minimal RHEL / Mac / Ubuntu / Suse etc versions?
- GTK 3.22 or which one?
- Anything else?

**Comment by akurtakov** [comment]
> @akurtakov, @sravanlakkimsetti and all who care:
> 
> It would be nice we would finally create a plan for 4.28 :-)
> 
> I can do that boring work, but first few things should be made clear.
> 
> Do we have a clear understanding / agreement regarding "target requirements"?
> 
>     * Java 17 is minimal supported one. Should be agreed / announced already.

Already announced.

> 
>     * What about minimal RHEL / Mac / Ubuntu / Suse etc versions?

Latest Linux versions only according to me. Mac is out of my world so can't say anything.

> 
>     * GTK 3.22 or which one?

Gtk 3.22. I don't see much reason to bump to 3.24 now as both are really out of active development . Gtk 4.x port is not yet compiled by the builds so nothing on this front.

> 
>     * Anything else?

Nothing from my side.

**Comment by iloveeclipse** [comment]
Project plan was created, see
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/33
- https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/34

Note: this is not correct:

> In general, the 4.28 release of the Eclipse Project is developed on Java SE 11 VMs. As such, the Eclipse SDK as a whole is targeted at all modern, desktop Java VMs. Most functionality is available for Java SE 11 level development everywhere, and extended development capabilities are made available on the VMs that support them.

11 must be replaced with 17

@elsazac : could you please address that?
Thanks.

**Comment by elsazac** [comment]
@iloveeclipse I have changed it from 11 to 17. https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/34

**Comment by iloveeclipse** [comment]
> @iloveeclipse I have changed it from 11 to 17. [eclipse-platform/www.eclipse.org-eclipse#34](https://github.com/eclipse-platform/www.eclipse.org-eclipse/pull/34)

OK, I saw the out-of-date cached version. Thanks. I think we are done here then.
