### ISSUE TITLE
Add an action to check PR's don't have merge commits

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#214]
In 99% if cases in the platform (except "next" Java branch work in JDT) we won't have merge commits in PR's, to have a clean and easy to understand git history.

However, most of github contributors simply don't know that, don't care in general and so do whatever possible with git in their PR's. This causes frustration on both sides.

There is a way to "disable" merge commits in general in the repo, but sometimes it is needed, and it also doesn't check PR's commits, only on "merge" action.

I think better would be if PR validation fails automatically.

We should check if there is a Github Action available that can be configured for all platfrom repo and show an error on PR's with merge commits.

**Comment by akurtakov** [comment]
Google gives https://github.com/marketplace/actions/block-merge-commits , I haven't tried it but sounds like what you look for .

**Comment by iloveeclipse** [comment]
@laeubi : if I'm not mistaken, you are familiar with github actions configuration. Is that something that can be done per organization or must be done per repo? Would you volonteer to provide an example in platform? If that requitres some admin rights, we can ask infra team to enable that automatically for Platform / JDT / PDE / Equinox.

**Comment by laeubi** [comment]
I'll try to unify builds of "platform" the next days/weeks a bit and can take this also into account, I  don't think we need special rights here, but if so I can also request one from the infra-team.

But to be sure, the problem is that for example instead of a rebase one do a merge master into a PR to make it up-to-date?

**Comment by iloveeclipse** [comment]
> the problem is that for example instead of a rebase one do a merge master into a PR to make it up-to-date?

Exact. See for example this PR that used merge few times: https://github.com/eclipse-jdt/eclipse.jdt.ui/pull/439/commits

**Comment by laeubi** [comment]
If you are a repository owner you also might want to disable the first but enable the second option:
![grafik](https://user-images.githubusercontent.com/1331477/225880708-ec0eb6a7-47ae-478d-aa3f-34f9bca5bd0d.png)

**Comment by iloveeclipse** [comment]
As I've wrote above, for JDT we need merge commits. 

But I think we can disable them for Platform. The only use case where will need a merge will be repo merging, and that happens not every day, so we can enable merges for only that commit.

**Comment by laeubi** [comment]
The "suggest updating pull request branches" is still very useful :-)
If your happy with the workflow at JDT-ui I can submit it as a reusable one here for releng as well.

**Comment by iloveeclipse** [comment]
>  If your happy with the workflow at JDT-ui I can submit it as a reusable one here for releng as well.

Sure, please go ahead, I'm happy.

**Comment by iloveeclipse** [comment]
@laeubi : can you please also provide PR's for PDE / Equanox?

**Comment by laeubi** [comment]
@iloveeclipse I'll try to do so the next days when I rework the actions to use the shared workflow from aggregator repo!

**Comment by HannesWell** [comment]
> @laeubi : can you please also provide PR's for PDE / Equinox?

For equinox and PDE merge commits are disabled for PRs and I see no use-case where this is necessary. Can you tell if that would also magically remove merge commits if a PR is merged with rebase-and-merge?

If not then such workflow would be really helpful, if yes then it is nice to have.

**Comment by iloveeclipse** [comment]
> Can you tell if that would also magically remove merge commits if a PR is merged with rebase-and-merge?

No magic here. Human brain will be still needed for some time. The action will just help people with merge commits in the PR understanding the problem without committers asking them "please undo merges and rebase instead".
