### ISSUE TITLE
Missing category for "Bytecode Outline View" and "Java AST View"

### ISSUE THREAD

**Issue by howlger** [eclipse-platform/eclipse.platform.releng#215]
When installing the _Bytecode Outline View_ or the _Java AST View_ via _Help > Install New Software..._, _Group items by category_ has to be disabled, otherwise they will not be listed.

This applies to both, the update sites of the Eclipse project, e.g. `https://download.eclipse.org/eclipse/updates/latest`, and the Eclipse Simultaneous Release update sites, e.g. `https://download.eclipse.org/releases/latest`. For the latter, I would guess that this would in [org.eclipse.simrel.build.git](https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/) require editing both [`ep.aggrcon`](https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/tree/) and [`simrel.aggr`](https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/tree/simrel.aggr).

Features not in a category:
- **_Bytecode Outline View_** - `org.eclipse.jdt.bcoview.feature.feature.group`
- **_Java AST View_** - `org.eclipse.jdt.astview.feature.feature.group`

**Comment by howlger** [comment]
I don't know either. I would have expected the categories in this [`category.xml`,](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/eclipse.platform.repository/category.xml) file similar to [`category.xml`](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/eclipse.platform.releng.tychoeclipsebuilder/java20patch/eclipse.releng.repository.java20patch/category.xml) for the Java 20 patch, but that is not the case. Also I don't know the `.aggrcon`/`.aggr` file format.

I guess @merks knows how to do it.

**Comment by merks** [comment]
Yes, I know what to do.   I'll pin this issue to a tab and get to in shortly.

**Comment by merks** [comment]
It's slightly tricky because it's not mentioned explicitly in ep.aggrcon.  It's on the train because it's included by the SDK feature which is explicitly mentioned, so I will need to add an explicitly categorized reference to it.  No doubt I should do that for the other new views too.  I'll look tomorrow at what's all included by the SDK feature to see if there is anything else interesting that might be similarly overlooked (uncategorized but interesting to install).

**Comment by reckart** [comment]
Shouldn't the new fews be auto-installed if they are part of a feature being upgraded. I.e. when I upgraded the Java JDT stuff from 2023-12 to 2023-03, I wonder why e.g. the bytecode view was not auto-added (in particular considering it was praised in the announcement video).

**Comment by howlger** [comment]
> Shouldn't the new views be auto-installed if they are part of a feature being upgraded? I.e. when I upgraded the Java JDT stuff from 2023-12 to 2023-03, I wonder why e.g. the bytecode view was not auto-added (in particular considering it was praised in the announcement video).

Yes, but that's a different thing. The _Bytecode_ view has been added to the IDE Java packages by the [EPP project](https://projects.eclipse.org/projects/technology.packaging) in [commit 13e081d](https://git.eclipse.org/c/epp/org.eclipse.epp.packages.git/commit/?id=13e081d7ac95f65ffc95439fe80fe8a1c68290e4) (see [bug 581619](https://bugs.eclipse.org/bugs/show_bug.cgi?id=581619)). `installMode="root"` makes it a feature that can be uninstalled separately. But I suspect that this is not enough to get it when upgrading a product that did not previously contain it (because it is unclear whether it was previously installed at some point and then explicitly uninstalled, so you don't want to get it back by upgrading). If at all, it might be possible via some `p2.inf` magic. I was not aware of all this when I made the video. Anyway, thank you for watching my video. 😉

**Comment by merks** [comment]
Yes the installMode specifies to install it in the product at build time but there is no requirement on it in the p2 metadata so it can be uninstalled and will of course not be automatically installed.  Such is how it was specified.

**Comment by howlger** [comment]
> Yes the installMode specifies to install it in the product at build time but there is no requirement on it in the p2 metadata so it can be uninstalled and will of course not be automatically installed. Such is how it was specified.

Is there any way that you can get it on upgrade, with the possibility to uninstall it, but if you uninstall it, you shouldn't get it again on the next upgrade?

**Comment by merks** [comment]
Sorry, I mixed up my issues with the above PR...

This is the change for simrel to add all three new view features such that they are categorized the same way as the JDT feature.

https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/200683

I'll check the report in while to be sure they are indeed categorized properly in the staging repo before closing this issue.

**Comment by merks** [comment]
These are present here:

https://download.eclipse.org/staging/2023-06/buildInfo/archive/download.eclipse.org/staging/2023-06/

Like this:

![image](https://user-images.githubusercontent.com/208716/226104463-5f5e0ff5-2ba3-4976-83e6-d8f01c6cf3c0.png)

The feature names are not so consistent, but that's up to JDT to define...
