### ISSUE TITLE
Maven export generates wrong dependencies (com.sun.jna instead of net.dev.java.jna)

### ISSUE THREAD

**Issue by kenwenzel** [eclipse-platform/eclipse.platform.releng#243]
Exported bundles on Maven Central have wrong dependencies.

For example the bundle org.eclipse.urischeme:jar:1.1.100 a dependency to
com.sun.jna:jar:[4.5.1,6.0.0) that does not exist on Maven Central.

The POM can be found at:
https://search.maven.org/remotecontent?filepath=org/eclipse/platform/org.eclipse.urischeme/1.1.0/org.eclipse.urischeme-1.1.0.pom

The following error happens when buildung a project with Maven:
```
Failed to collect dependencies at org.eclipse.platform:org.eclipse.ui.workbench:jar:3.116.0 -> 
org.eclipse.platform:org.eclipse.e4.ui.workbench.addons.swt:jar:1.2.100 -> 
org.eclipse.platform:org.eclipse.e4.ui.workbench.renderers.swt:jar:0.14.0 -> 
org.eclipse.platform:org.eclipse.e4.ui.workbench.swt:jar:0.14.1000 -> org.eclipse.platform:org.eclipse.urischeme:jar:1.1.100 -> 
com.sun.jna:com.sun.jna:jar:[4.5.1,6.0.0)
```

Another source of the problem is that the exported Maven POMs use version ranges for dependencies instead of fixed versions.
This regularly leads to broken builds if a newer version of some bundle is available on Maven Central. The generated POMs must use FIXED versions for dependencies.

**Comment by mickaelistria** [comment]
Artifact should be https://central.sonatype.com/artifact/net.java.dev.jna/jna/5.13.0/overview

**Comment by merks** [comment]
Of course we can't republish old things, but the latest released version looks fine:

https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.urischeme/1.3.0/org.eclipse.urischeme-1.3.0.pom

**Comment by kenwenzel** [comment]
Maybe you could publish BOMs also for the older versions:
https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#bill-of-materials-bom-poms

These BOMs could also exclude non-existent dependencies.

**Comment by mickaelistria** [comment]
@kenwenzel I don't think your use-case is supported by the current contributors community, it's about using older versions and running on older versions of runtime the project doesn't support any more. So you'll hardly find some contributor to do take some work here unless you can convince them of bigger benefits working on this issue compared to other pending issues. Usually, if you need some support for older versions, the best chance would be that you contribute to it; eg here, you generate the bom and tell us how to publish from the project CI and we could do it for you. Another approach if you need support for unsupported versions/use-cases, is that you find someone to hire for it. Some of the active contributors to the project are freelancers, you can try to reach out to them and buy their service.
In the meantime, our recommendation is usually that you consider just using the latest release and updates often to remain current, and benefits from the improvements that have been implemented over the last years.
