### ISSUE TITLE
The published pom for org.eclipse.osgi.util 3.7.0 on maven central is wrong

### ISSUE THREAD

**Issue by jmini** [eclipse-platform/eclipse.platform.releng#52]
Since the original issue https://github.com/eclipse-equinox/equinox.bundles/issues/54 has too many comments, I decided to open a new one.

`org.eclipse.platform:org.eclipse.equinox.preferences:3.10.0` is not the only broken pom (see [org.eclipse.equinox.preferences-3.10.0.pom](https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.equinox.preferences/3.10.0/org.eclipse.equinox.preferences-3.10.0.pom) on maven central).

There is also:
`org.eclipse.platform:org.eclipse.osgi.util:3.7.0`. See: [org.eclipse.osgi.util-3.7.0.pom](https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi.util/3.7.0/org.eclipse.osgi.util-3.7.0.pom)

The groupId `org.osgi.util` does not exist and should be `org.osgi`.

---

This is already fixed by https://github.com/eclipse-platform/eclipse.platform.releng/pull/48 there is a new mapping:

https://github.com/eclipse-platform/eclipse.platform.releng/blob/06dad075b626766ec264d3626c01bedb5f4eba60/publish-to-maven-central/SDK4Mvn.aggr#L70

---

Probably not so many people are impacted (because it does not seems to be a transitive dependency of jdt.core), but it would be healthy to published a fixed pom for this artifact as well.

**Comment by akurtakov** [comment]
https://repo1.maven.org/maven2/org/eclipse/platform/org.eclipse.osgi.util/3.7.1/ is already on maven central.

**Comment by jmini** [comment]
Sorry I looked here:
https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.osgi.util

<img width="1146" alt="Screenshot of mvnrepository" src="https://user-images.githubusercontent.com/1222165/174013488-75496b95-c717-402c-83aa-eb46ca5df160.png">

This viewer is very convenient but is always behind with the display of newer artifact.

**Comment by HannesWell** [comment]
Thanks for your check.
Just for reference the issue you found was already addressed in https://github.com/eclipse-equinox/equinox.framework/issues/70

Nevertheless it is good to know that there are no more flaws (in the dependencies) in the published poms. 👍🏽
