### ISSUE TITLE
No Windows tests since I20220620-1050

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#56]
Haven't checked why, but Windows tests aren't running since I20220620-1050.
See https://download.eclipse.org/eclipse/downloads/

**Comment by iloveeclipse** [comment]
Thanks Sravan.

**Comment by iloveeclipse** [comment]
Just for the record: here is the "Azure agent" instance https://ci.eclipse.org/releng/computer/qa6xd-win11/

This was offline, now it was restarted and runs ep425Y-unit-win32-java11 build.

I hope next one will be https://ci.eclipse.org/releng/view/Automated%20tests/job/ep425I-unit-win32-java11/

**Comment by akurtakov** [comment]
Builds are back to a bit under 4h and haven't failed lately. Closing.
