### ISSUE TITLE
Unsatisfied constraint: 'Import-Package: com.ibm.icu.text; version="3.8.1"'

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.releng#69]
We see a severe issue with PDE/SDK in M1.

Bundles that import `com.ibm.icu.text;version="3.8.1"` package show PDE validation errors and also can't be activated on startup, if only  `com.ibm.icu` bundle that is shipped with SDK is available in the platform.

This affects GEF and Webtools installed "offline" (not by using update sites connected to internet).

Example bundle with this MANIFESt.MF can't be started in pure SDK:
```
Manifest-Version: 1.0
Bundle-ManifestVersion: 2
Bundle-Name: IcuTest
Bundle-SymbolicName: IcuTest;singleton:=true
Bundle-Version: 1.0.0.qualifier
Automatic-Module-Name: IcuTest
Bundle-RequiredExecutionEnvironment: JavaSE-11
Import-Package: com.ibm.icu.text;version="3.8.1"
Require-Bundle: org.eclipse.ui
Bundle-ActivationPolicy: lazy
```

![image](https://user-images.githubusercontent.com/964108/177943192-106cd184-c1de-45c2-8e29-ffe90d768138.png)

```
!ENTRY IcuTest 4 0 2022-07-08 09:50:15.311
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: IcuTest [311]
  Unresolved requirement: Import-Package: com.ibm.icu.text; version="3.8.1"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1847)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1840)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1781)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1745)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1667)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by mickaelistria** [comment]
Upstream icu4j bundles that are now shipped by the SDK don't have a version on package export, so they cannot satisfy such ` Import-Package: com.ibm.icu.text; version="3.8.1"` requirement. The solution for consumer is to remove the version on the package requirement.
Are those installed with p2 (even if offline)? p2 is supposed to report the issue during installation.

I would not qualify it as a bug, as shipping packages versions for upstream jars like ICU is not part of any API contract or similar, so it's not something clients are supposed to rely on. However, we can add a note about it in the migration notes.

**Comment by mickaelistria** [comment]
I suggested https://github.com/eclipse-platform/eclipse.platform.common/pull/50 to the documentation.

**Comment by iloveeclipse** [comment]
> Upstream icu4j bundles that are now shipped by the SDK don't have a version on package export

Should they? I assume the project is https://github.com/unicode-org/icu/tree/main/icu4j/main/classes/core and bug tracker https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues/?filter=allissues .

> The solution for consumer is to remove the version on the package requirement.

The consumer consumes GEF 3, that can't be changed because it is already released and updating to a new GEF that might have this fix will mean re-validation of the entire product.

Beside this, isn't that a good practice to set ranges - either to make sure specific API is available or that specific API isn't broken? So recommendation now is not to follow OSGI best practices?

Also it is strange to see SDK providing "crippled" icu library that can't be used by clients that follow the "OSGI best practices". Also it means for everyone affected to change build files and make sure the target platform will have a "copy" of the very same library but with proper metadata. Once these update sites that offer old icu bundle disappear, the fun will start again...

**Comment by mickaelistria** [comment]
> Should they? I assume the project is https://github.com/unicode-org/icu/tree/main/icu4j/main/classes/core and bug tracker https://unicode-org.atlassian.net/jira/software/c/projects/ICU/issues/?filter=allissues .

It's indeed usually a good practice to maintain versions on export packages. However, versions on packages are not something that can just be put randomly (a bit like Orbit does). Wrong versions is as bad as no version.

> The consumer consumes GEF 3, that can't be changed because it is already released and updating to a new GEF that might have this fix will mean re-validation of the entire product.

OK, as mentioned on the PR about doc, one solution is to force inclusion of Orbit's icu in the product. p2 would actually take care of it.

> Beside this, isn't that a good practice to set ranges - either to make sure specific API is available or that specific API isn't broken? So recommendation now is not to follow OSGI best practices?

The recommendation is to work with upstream jars instead of Orbit variants (which are also bogus with fake/incorrect versions). None of those provider do implement OSGi best practices nor proper metadata.
The workaround is for products that need it to embed the Orbit variant

**Comment by merks** [comment]
The change to use the direct-from-maven version appears to be kind of gratuitous because it's not even a new version but rather (almost) the same version with different details:

![image](https://user-images.githubusercontent.com/208716/177965367-26370228-3d7f-489e-849e-bd3c42596ed1.png)

**Comment by laeubi** [comment]
> Also it is strange to see SDK providing "crippled" icu library that can't be used by clients that follow the "OSGI best practices".

The best would be to report this to the author of the library so we can upgrade to a more OSGi friendly version. The more interesting question is if they follow any semantic version scheme or if versions are arbitrarily choosen anyways.

**Comment by laeubi** [comment]
Just as a note here, the problem itself is because GEF seem to use the SDK as source of third-party libraries and instead should use either Maven, Orbit, ... whatever and then ship these in their updatesite if one wants to be super-correct.

**Comment by ewillink** [comment]
QVTo broke in 2018 when JDT started using com.ibm.icu 4.0.0. Reviewing the code revealed that the very limited usage seemed to represent fairly prehistoric practices that were needed when Unicode was evolving. It proved pretty easy to rewrite all usage with more modern (Java 5) support. I recommend eliminating com.ibm.icu completely.

**Comment by mickaelistria** [comment]
> I recommend eliminating com.ibm.icu completely.

That's actually one of the current goals for some Platform committers (at least @akurtakov as far as I know), and there is a good hope than in a not-too-distant future, ie before september release, requirement on icu4j gets removed.
Same reasoning can apply to many 3rd party libs: Java standard API has much evolved and we can probably find more instances where we can replace a dependency by plain Java usage. Each occurrence is actually a major win.

**Comment by iloveeclipse** [comment]
Created patches for:
* GEF classic https://github.com/eclipse/gef-classic/pull/91
* Webtools common https://git.eclipse.org/r/c/webtools-common/webtools.common/+/194676
* Webtools source editing https://git.eclipse.org/r/c/sourceediting/webtools.sourceediting/+/194679

**Comment by akurtakov** [comment]
I think this one can be closed as nothing more is supposed to be done on our side.

**Comment by mickaelistria** [comment]
Indeed, https://github.com/eclipse-platform/eclipse.platform.common/blob/master/bundles/org.eclipse.platform.doc.isv/porting/4.25/incompatibilities.html documents how to embrace newer bundles.

**Comment by trancexpress** [comment]
> The change to use the direct-from-maven version appears to be kind of gratuitous because it's not even a new version but rather (almost) the same version with different details:

Ed, can you take a look here? https://github.com/eclipse/emf-validation/pull/4

I can't ping you on the PR for some reason.

**Comment by pcdavid** [comment]
> > I recommend eliminating com.ibm.icu completely.
> 
> That's actually one of the current goals for some Platform committers (at least @akurtakov as far as I know), and there is a good hope than in a not-too-distant future, ie before september release, requirement on icu4j gets removed.

For reference, [Bugzilla #562582](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562582) mentioned:

> Eclipse PMC agreed that ICU4J support is gone now so implementations using it will actively be replaced with built-in JVM functionality in internal code. Wherever it's exposed as API the standard 2 years deprecation period applies. 
Right now the plan is to remove ICU4J from Eclipse SDK for the 2022-06 release.

**Comment by merks** [comment]
The generated report shows a number of dependencies remaining today:

![image](https://user-images.githubusercontent.com/208716/182314881-bf23f48f-0165-49e1-af87-1c823366bbe4.png)

**Comment by akurtakov** [comment]
ICU4J is still used but IIRC o.e.core.databinding APIs that use it are deprecated now and we wait for the deprecation period before we can remove these API and thus the ICU4J usage.

**Comment by vogella** [comment]
> 

Planned for next release https://git.eclipse.org/c/platform/eclipse.platform.common.git/tree/bundles/org.eclipse.platform.doc.isv/porting/removals.html#n640

**Comment by flaviodonze** [comment]
It looks like this fix did not make it in the 2022-09 release (at least for GEF):
![grafik](https://user-images.githubusercontent.com/24522870/190332131-6a7179f2-37b4-4d35-a7c1-3eb7b565a5c1.png)
![grafik](https://user-images.githubusercontent.com/24522870/190332405-5cc6cb4c-a7f1-4671-a07b-09840bb3779c.png)

**Comment by iloveeclipse** [comment]
I wonder which GEF is being used here.
AFAIK the "right" one (without ICU version on import) should be https://github.com/eclipse/gef-classic, see https://github.com/eclipse/gef-classic/blob/691b10b78c5eb33a0e5d9ce9041430c4d90ad276/org.eclipse.gef/META-INF/MANIFEST.MF#L5.

**Comment by mickaelistria** [comment]
> It looks like this fix did not make it in the 2022-09 release (at least for GEF):

This should be reported to GEF.

**Comment by merks** [comment]
Specifically I think it should be reported here:

https://github.com/eclipse/gef-classic/issues
