### ISSUE TITLE
[19] Y builds are not running with Java 19

### ISSUE THREAD

**Issue by SarikaSinha** [eclipse-platform/eclipse.platform.releng#80]
https://download.eclipse.org/eclipse/downloads/drops4/Y20220728-1000/testResults.php
Y builds should run with Java 19 also.

@sravanlakkimsetti

**Comment by akurtakov** [comment]
I see test results for Ybuild on Java 19 https://download.eclipse.org/eclipse/downloads/drops4/Y20220728-1000/testResults.php . Closing.
