### ISSUE TITLE
https://download.eclipse.org/eclipse/updates/4.25-I-builds contains empty categories

### ISSUE THREAD

**Issue by vogella** [eclipse-platform/eclipse.platform.releng#82]
We have three categories which are empty in our update site:

API Tools...
CVS Client
Releng Tools

![image](https://user-images.githubusercontent.com/139910/182772342-ce4ccd07-a4e3-4dcf-be40-25b410340055.png)

Should we remove these categories? cc @vik-chand @akurtakov ?

**Comment by merks** [comment]
I think empty categories make no sense...

**Comment by akurtakov** [comment]
CVS client and APItools are gone now so we can remove these. Releng tools was supposed to have releng.tools.feature at least so this one we have to investigate and fix.

**Comment by akurtakov** [comment]
Actually releng tools is no longer published to I-build repo so this one should be removed too.

**Comment by akurtakov** [comment]
Fixed by @sravanlakkimsetti
